# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.version.version

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.rand(2,3,5)
print(a)

[[[0.13989451 0.92236533 0.62829708 0.15369002 0.34328318]
  [0.5809308  0.78084653 0.22955938 0.38720635 0.51336415]
  [0.38368866 0.95689818 0.18845939 0.13011187 0.82766514]]

 [[0.23870313 0.50531237 0.7418277  0.74225523 0.61134468]
  [0.66177606 0.7659149  0.47026408 0.62211751 0.01668275]
  [0.76423924 0.79425184 0.21750818 0.05203944 0.86920383]]]


In [ ]:
# Method 2

In [ ]:
# Method 3

#### 4. Print *a*.


In [5]:
# your code here
print(a)

[[[0.13989451 0.92236533 0.62829708 0.15369002 0.34328318]
  [0.5809308  0.78084653 0.22955938 0.38720635 0.51336415]
  [0.38368866 0.95689818 0.18845939 0.13011187 0.82766514]]

 [[0.23870313 0.50531237 0.7418277  0.74225523 0.61134468]
  [0.66177606 0.7659149  0.47026408 0.62211751 0.01668275]
  [0.76423924 0.79425184 0.21750818 0.05203944 0.86920383]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [21]:
# your code here
import numpy as np

b = np.ones( (5, 2, 3) , dtype=np.int64)

#### 6. Print *b*.


In [22]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [23]:
# your code here
a.shape

(2, 3, 5)

In [24]:
b.shape

(5, 2, 3)

In [ ]:
# a and b have different shapes

#### 8. Are you able to add *a* and *b*? Why or why not?


In [25]:
# your answer here

print(a+b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
#We can't add a and b because they have different shapes !

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c= np.transpose(b, axes=(1,2,0))
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [31]:
# your code/answer here
d = a+c
print(d)

[[[1.13989451 1.92236533 1.62829708 1.15369002 1.34328318]
  [1.5809308  1.78084653 1.22955938 1.38720635 1.51336415]
  [1.38368866 1.95689818 1.18845939 1.13011187 1.82766514]]

 [[1.23870313 1.50531237 1.7418277  1.74225523 1.61134468]
  [1.66177606 1.7659149  1.47026408 1.62211751 1.01668275]
  [1.76423924 1.79425184 1.21750818 1.05203944 1.86920383]]]


In [29]:
a.shape

(2, 3, 5)

In [30]:
c.shape

(2, 3, 5)

In [ ]:
#Sum of a and c works now because a and c have the same shape.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [32]:
# your code/answer here
print(a)

[[[0.13989451 0.92236533 0.62829708 0.15369002 0.34328318]
  [0.5809308  0.78084653 0.22955938 0.38720635 0.51336415]
  [0.38368866 0.95689818 0.18845939 0.13011187 0.82766514]]

 [[0.23870313 0.50531237 0.7418277  0.74225523 0.61134468]
  [0.66177606 0.7659149  0.47026408 0.62211751 0.01668275]
  [0.76423924 0.79425184 0.21750818 0.05203944 0.86920383]]]


In [33]:
print(d)

[[[1.13989451 1.92236533 1.62829708 1.15369002 1.34328318]
  [1.5809308  1.78084653 1.22955938 1.38720635 1.51336415]
  [1.38368866 1.95689818 1.18845939 1.13011187 1.82766514]]

 [[1.23870313 1.50531237 1.7418277  1.74225523 1.61134468]
  [1.66177606 1.7659149  1.47026408 1.62211751 1.01668275]
  [1.76423924 1.79425184 1.21750818 1.05203944 1.86920383]]]


In [ ]:
# d = a + matrix identity of shape (2,3,5)

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here
e = a*c
print(e)

[[[0.13989451 0.92236533 0.62829708 0.15369002 0.34328318]
  [0.5809308  0.78084653 0.22955938 0.38720635 0.51336415]
  [0.38368866 0.95689818 0.18845939 0.13011187 0.82766514]]

 [[0.23870313 0.50531237 0.7418277  0.74225523 0.61134468]
  [0.66177606 0.7659149  0.47026408 0.62211751 0.01668275]
  [0.76423924 0.79425184 0.21750818 0.05203944 0.86920383]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here

# I confirm that e = a = a*c ! 
# c is the identity matrix which implies that multiplying a by c = a ! 

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
# your code here
np.max(d)

1.9568981766851041

In [45]:
np.min(d)

1.0166827484867778

In [38]:
np.mean(d)

1.507990049698511

In [46]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [47]:
# your code here
import numpy as np
f = np.empty ((2, 3, 5))
print(f)

[[[0.13989451 0.92236533 0.62829708 0.15369002 0.34328318]
  [0.5809308  0.78084653 0.22955938 0.38720635 0.51336415]
  [0.38368866 0.95689818 0.18845939 0.13011187 0.82766514]]

 [[0.23870313 0.50531237 0.7418277  0.74225523 0.61134468]
  [0.66177606 0.7659149  0.47026408 0.62211751 0.01668275]
  [0.76423924 0.79425184 0.21750818 0.05203944 0.86920383]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here
f=[]
for x in np.nditer(d):
        if d_min < x < d_mean:
                f += [25]
        if d_mean < x < d_max:
                f += [75]
        if x == d_mean:
                f += [50]
        if x == d_min:
                f += [0]
        if x == d_max:
                f += [100]
f = np.reshape(f, d.shape)
print(f)


[[[ 25  75  75  25  25]
  [ 75  75  25  25  75]
  [ 25 100  25  25  75]]

 [[ 25  25  75  75  75]
  [ 75  75  25  75   0]
  [ 75  75  25  25  75]]]


In [49]:
print(d)

[[[1.13989451 1.92236533 1.62829708 1.15369002 1.34328318]
  [1.5809308  1.78084653 1.22955938 1.38720635 1.51336415]
  [1.38368866 1.95689818 1.18845939 1.13011187 1.82766514]]

 [[1.23870313 1.50531237 1.7418277  1.74225523 1.61134468]
  [1.66177606 1.7659149  1.47026408 1.62211751 1.01668275]
  [1.76423924 1.79425184 1.21750818 1.05203944 1.86920383]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code heref=[]

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here